 workflows:
    ionic-capacitor-android-workflow:
          name: Ionic Capacitor Android Workflow
          max_build_duration: 120
          instance_type: mac_pro
          environment:
              vars:
                # Android Keystore environment variables
                CM_KEYSTORE: Encrypted(...) # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: Encrypted(...) # <-- Put your encrypted keystore alias username here
              node: latest
          triggering:
              events:
                  - push
                  - tag
                  - pull_request
              branch_patterns:
                  - pattern: develop
                    include: true
                    source: true
          scripts:
              - name: Install npm dependencies for Ionic project
                script: |
                  npm install
              - name: Set Android SDK location
                script: |
                  echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
              - name: Set up keystore
                script: |
                  echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                  cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                  storePassword=$CM_KEYSTORE_PASSWORD
                  keyPassword=$CM_KEY_ALIAS_PASSWORD
                  keyAlias=$CM_KEY_ALIAS_USERNAME
                  storeFile=/tmp/keystore.keystore
                  EOF
              - name: Update dependencies and copy web assets to native project
                script: |
                  # npx cap copy # <- use this is you don't need to update native dependencies
                  npx cap sync # <- update native dependencies and copy web assets to native project
              - name: Build Android release
                script: |
                  cd android
                  ./gradlew assembleRelease
          artifacts:
              - android/app/build/outputs/**/*.apk
          publishing:
              email:
                  recipients:
                      - nihal@nevercode.io
                  notify:
                    success: true     # To not receive a notification when a build succeeds
                    failure: false     # To not receive a notification when a build fails
